service: capsule-service
package:
  version: 0.0.1-SNAPSHOT
  artifact: ./application/target/${self:service}-${self:package.version}-${self:provider}.jar
provider:
  name: aws
  runtime: java11
  region: us-east-2
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    APPLICATION_ENVIRONMENT: Dev
    CLOUD_REGION: US_East_2
functions:
  createCapsule:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/create
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
  updateCapsule:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/update
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: updateFunction
  disableCapsule:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/disable
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: disableFunction
  getCapsule:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/findById
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getFunction
  bookmarkCapsule:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/bookmark
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: addBookmarkFunction
  approveCapsule:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/approve
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: approveFunction
  getEditorsPickCapsules:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/getEditorsPick
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getEditorsPickFunction
  getMyFeedCapsules:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/getMyFeed
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getMyFeedFunction
  getTrendingCapsules:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/getTrending
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getTrendingFunction
  recommendCapsule:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/recommend
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: recommendFunction
  searchCapsuleByTopic:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: capsule/searchByTopic
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: searchByTopicFunction
resources:
  Resources:
    capsuleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Capsule
        AttributeDefinitions:
          - AttributeName: capsuleId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: topicCode
            AttributeType: S
          - AttributeName: editorsPick
            AttributeType: B
          - AttributeName: recommendations
            AttributeType: N
        KeySchema:
          - AttributeName: capsuleId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: topicGSI
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: topicCode
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: editorsPickGSI
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: editorsPick
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: trendingGSI
            KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: recommendations
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1